# .travis.yml
language: node_js
git:
  depth: 1
node_js:
  - '7.0.0'
before_install:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
script:
  - npm run travis
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then npm run publish-branch || true; fi'
notifications:
  email: false
deploy:
  - provider: npm
    email: jim@vigour.io
    api_key: ${NPM_TOKEN}
    on:
      branch: master
